# deploy.yml
- name: Deploy Docker Container on Remote Server
  hosts: all
  become: yes
  tasks:
    - name: Stop existing container
      shell: docker stop myapp || true

    - name: Remove existing container
      shell: docker rm myapp || true

    - name: Remove existing image
      shell: docker rmi myapp:latest || true

    - name: Copy Docker image from Jenkins to target server
      copy:
        src: /tmp/myapp.tar
        dest: /tmp/myapp.tar

    - name: Load Docker image
      shell: docker load -i /tmp/myapp.tar

    - name: Run the container
      shell: docker run -d --name myapp -p 5000:5000 myapp:latest
