
---
- name: Deploy Flask App Container
  hosts: web
  become: true

  tasks:
    - name: Install required packages
      yum:
        name:
          - docker
        state: present
        update_cache: yes

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: true

    - name: Load Docker image from tar
      shell: docker load < /tmp/myapp.tar

    - name: Remove old container if exists
      shell: docker rm -f flaskapp || true

    - name: Run the Docker container
      shell: docker run -d --name flaskapp -p 80:5000 myapp:latest
